title: Danish Rasheed
logo: danish_circle.png
description: Experienced Professional with a demonstrated history of working in the information technology and services industry. A very good team-player.
# show_downloads: true
theme: jekyll-theme-minimal
